<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-21T09:11:13Z" name="APISuite" finished-at="2021-09-21T09:11:15Z" duration-ms="2420">
    <groups>
    </groups>
    <test started-at="2021-09-21T09:11:13Z" name="Delete Customer API Test" finished-at="2021-09-21T09:11:15Z" duration-ms="1784">
      <class name="com.w2a.APITestingFramework.testcases.DeleteCustomerTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.w2a.APITestingFramework.testcases.DeleteCustomerTest@2d36e77e]" started-at="2021-09-21T14:41:13Z" name="setUp" finished-at="2021-09-21T14:41:13Z" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.DeleteCustomerTest@2d36e77e]" started-at="2021-09-21T14:41:13Z" name="deleteCustomer" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="1735" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_KGc23HaZHGY6La}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[ID key is not present in response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: ID key is not present in response expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.w2a.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.w2a.APITestingFramework.testcases.DeleteCustomerTest@2d36e77e]" started-at="2021-09-21T14:41:15Z" name="tearDown" finished-at="2021-09-21T14:41:15Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.APITestingFramework.testcases.DeleteCustomerTest -->
    </test> <!-- Delete Customer API Test -->
    <test started-at="2021-09-21T09:11:13Z" name="Create Customer API Test" finished-at="2021-09-21T09:11:15Z" duration-ms="2420">
      <class name="com.w2a.APITestingFramework.testcases.CreateCustomerTest">
        <test-method signature="ValidateCreateCustomerAPIWithInValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.CreateCustomerTest@23bff419]" started-at="2021-09-21T14:41:13Z" name="ValidateCreateCustomerAPIWithInValidSecretKey" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="1674" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=greakesh@123@gmail.com, name=Rakesh G, description=InvalidComment1}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.w2a.APITestingFramework.testcases.CreateCustomerTest.ValidateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIWithInValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.CreateCustomerTest@23bff419]" started-at="2021-09-21T14:41:15Z" name="ValidateCreateCustomerAPIWithValidSecretKey" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="667" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=grakesh628@gmail.com, name=RG, description=2comment}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIWithValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.CreateCustomerTest@23bff419]" started-at="2021-09-21T14:41:15Z" name="ValidateCreateCustomerAPIWithValidSecretKey" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="652" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rakesh.gundu@gmail.com, name=Rakesh Gundu, description=Adding first customer in framework by RG}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIWithValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.CreateCustomerTest@23bff419]" started-at="2021-09-21T14:41:15Z" name="ValidateCreateCustomerAPIWithValidSecretKey" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="670" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=rg@gmail.com, name=RG1, description=3rd Comment}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIWithValidSecretKey -->
        <test-method signature="ValidateCreateCustomerAPIWithValidSecretKey(java.util.Hashtable)[pri:0, instance:com.w2a.APITestingFramework.testcases.CreateCustomerTest@23bff419]" started-at="2021-09-21T14:41:15Z" name="ValidateCreateCustomerAPIWithValidSecretKey" data-provider="data" finished-at="2021-09-21T14:41:15Z" duration-ms="686" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=grak@gmail.com, name=RG2, description=4th comment}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateCreateCustomerAPIWithValidSecretKey -->
      </class> <!-- com.w2a.APITestingFramework.testcases.CreateCustomerTest -->
    </test> <!-- Create Customer API Test -->
  </suite> <!-- APISuite -->
</testng-results>
