<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-58M37A77" failures="1" tests="5" name="com.w2a.APITestingFramework.testcases.CreateCustomerTest" time="4.349" errors="0" timestamp="21 Sep 2021 09:11:16 GMT" skipped="0">
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIWithValidSecretKey" time="0.667"/>
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIWithValidSecretKey" time="0.652"/>
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIWithValidSecretKey" time="0.686"/>
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIWithValidSecretKey" time="0.670"/>
  <testcase classname="com.w2a.APITestingFramework.testcases.CreateCustomerTest" name="ValidateCreateCustomerAPIWithInValidSecretKey" time="1.674">
    <failure message="expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at com.w2a.APITestingFramework.testcases.CreateCustomerTest.ValidateCreateCustomerAPIWithInValidSecretKey(CreateCustomerTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- ValidateCreateCustomerAPIWithInValidSecretKey -->
</testsuite> <!-- com.w2a.APITestingFramework.testcases.CreateCustomerTest -->
